language: perl

env:
  - AUTOMATED_TESTING=1 PREREQS="rlib File::HomeDir File::Spec Term::ReadKey Module::Build"

install:
  # Prerequisites
  - "cpanm $PREREQS"

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log

install:
  # Prerequisites
  - "cpanm $PREREQS"

perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
