--- #YAML:1.0
name:               Term-ReadLine-Perl5
version:            1.04
abstract:           ~
author:  
    - Jordan M. Adler <jmadler@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  
    Term::ReadLine: 0
no_index:
    directory:
        - t
        - inc
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
